"""course level

Revision ID: 275215b989f5
Revises: 71ba8657a2bf
Create Date: 2026-07-07 09:41:01.330996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db  # custom column types (TZDateTime) referenced by autogenerate


# revision identifiers, used by Alembic.
revision: str = '275215b989f5'
down_revision: Union[str, Sequence[str], None] = '71ba8657a2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
